name: CI/CD for HTML Page

on:
  push:
    branches:
      - master

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: html-file
          path: index.html  # Ensure correct path

  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated to latest version
        with:
          name: html-file
          path: ./html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }}  # Using GitHub's default token
          publish_dir: ./html
